### ISSUE TITLE
8F Fire Extinguishing Gas Protection Room (지상 8층 소화가스실)

### ISSUE THREAD

**Issue by ETLink-StanleyPan** [ETLink/Samsung-SDS-Sangam-9F#17]
**Issue Description (이슈 설명):**
The detector lamp waas not lit on the receiver panel of the 8F fire extinguishing gas protection room when detecting fire at the lower section of the perforated plate in EPS#1 room on 9F of the server room.
(전산동 9층 EPS#1실 다공판 하부 감지기 화재 감지시 8층 소화가스실 수신반에서 감지기 램프 미점등.)

**Cause (원인):**
Refer to Issue Description (이슈 설명 참조)

**Action (조치):**
Program modification scheduled (프로그램 수정 예정 6/7)

**Result (결과):**
Ongoing (진행 중)

**Responsible (책임자):**
Samsung SDS (삼성 SDS)

**Reported Date (보고일):**
05/10/2019

**Action Date (조치일):**
없음

**Remarks (비고):**
없음

**Comment by JehyeonHeo** [comment]
After Issue Resolution. Program modified. And normal operation was checked.
![제목 없음10](https://user-images.githubusercontent.com/30972172/61508356-7893af80-aa24-11e9-9eae-443e15438500.png)
![제목 없음9](https://user-images.githubusercontent.com/30972172/61508357-7893af80-aa24-11e9-8883-ba8bc1e625d4.png)
![제목 없음8](https://user-images.githubusercontent.com/30972172/61508359-7893af80-aa24-11e9-9d1f-93256a019443.png)
![제목 없음7](https://user-images.githubusercontent.com/30972172/61508363-792c4600-aa24-11e9-94d6-a575c18961e8.png)
